version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=sql12.freesqldatabase.com
      - DB_USER=sql12801540
      - DB_PASSWORD=mfQbFZNDUi
      - DB_NAME=sql12801540
      - DB_PORT=3306
